# Generated by Django 5.2 on 2025-05-11 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=100)),
                ('parent_number', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_image', models.ImageField(blank=True, null=True, upload_to='staff/')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('administration', 'Administration'), ('finance', 'Finance'), ('academics', 'Academics'), ('health', 'Health'), ('maintenance', 'Maintenance')], max_length=20)),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('id_number', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_hired', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_image', models.ImageField(blank=True, null=True, upload_to='teachers/')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('tsc_number', models.CharField(max_length=20, unique=True)),
                ('id_number', models.CharField(max_length=20)),
                ('position', models.CharField(choices=[('teacher', 'Teacher'), ('hod', 'Head of Department'), ('deputy', 'Deputy Principal'), ('principal', 'Principal')], default='teacher', max_length=20)),
                ('subjects', models.CharField(max_length=100)),
                ('class_in_charge', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_hired', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_image', models.ImageField(blank=True, null=True, upload_to='students/')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('address', models.TextField()),
                ('tribe', models.CharField(blank=True, max_length=50, null=True)),
                ('religion', models.CharField(choices=[('christian', 'Christian'), ('muslim', 'Muslim'), ('hindu', 'Hindu'), ('other', 'Other')], max_length=20)),
                ('previous_school', models.CharField(blank=True, max_length=100, null=True)),
                ('health_details', models.TextField(blank=True, null=True)),
                ('admission_class', models.CharField(choices=[('form1', 'Form 1'), ('form2', 'Form 2'), ('form3', 'Form 3'), ('form4', 'Form 4')], max_length=10)),
                ('stream', models.CharField(choices=[('north', 'North'), ('south', 'South'), ('east', 'East'), ('west', 'West')], max_length=10)),
                ('admission_date', models.DateField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('student_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.parent')),
            ],
        ),
    ]
